# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property.
---
include:
  - board: nice_nano@2.0.0//zmk
    shield: corne_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
  - board: nice_nano@2.0.0//zmk
    shield: corne_right nice_view_adapter nice_view
